-- Schema para importar no RDS
CREATE DATABASE IF NOT EXISTS app_lab CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE app_lab;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  login VARCHAR(80) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  cep VARCHAR(9) NULL,
  logradouro VARCHAR(120) NULL,
  bairro VARCHAR(120) NULL,
  cidade VARCHAR(120) NULL,
  uf VARCHAR(2) NULL,
  numero VARCHAR(20) NULL,
  complemento VARCHAR(120) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
